### ISSUE TITLE
Not working aapt2 build error

### ISSUE THREAD

**Issue by sajedulsakib001** [mumumusuc/termux-android-sdk#1]
![Screenshot_2023-12-19-15-59-06-527_com.termux.jpg](https://github.com/mumumusuc/termux-android-sdk/assets/48612479/2e7440a9-5106-4903-8058-02ef78228484)

**Comment by mumumusuc** [comment]
have your edited `android/gradle.properties` like the [release](https://github.com/mumumusuc/termux-android-sdk/releases/tag/30.0.3) says?

**Comment by sajedulsakib001** [comment]
> have your edited `android/gradle.properties` like the [release](https://github.com/mumumusuc/termux-android-sdk/releases/tag/30.0.3) says?

Yes I did...Uploading Screenrecorder-2023-12-19-20-42-31-388.mp4 …

**Comment by sajedulsakib001** [comment]
> have your edited `android/gradle.properties` like the [release](https://github.com/mumumusuc/termux-android-sdk/releases/tag/30.0.3) says?

Yes I did...

https://github.com/mumumusuc/termux-android-sdk/assets/48612479/5e676d49-dd02-4409-bb58-8cbde33debce

**Comment by mumumusuc** [comment]
> > have your edited `android/gradle.properties` like the [release](https://github.com/mumumusuc/termux-android-sdk/releases/tag/30.0.3) says?
> 
> Yes I did...
> 
>  Screenrecorder-2023-12-19-20-42-31-388.mp4

Oh no, you copied the diff symbol '+', remove it.

**Comment by sajedulsakib001** [comment]
> > > have your edited `android/gradle.properties` like the [release](https://github.com/mumumusuc/termux-android-sdk/releases/tag/30.0.3) says?
> > 
> > Yes I did...
> > 
> >  Screenrecorder-2023-12-19-20-42-31-388.mp4
> 
> Oh no, you copied the diff symbol '+', remove it.

Thanks, bro! You are the most helpful person. ❤️☺️☺️ And please, keep this project up-to-date.
