### ISSUE TITLE
Don't understand 

### ISSUE THREAD

**Issue by L4R-777** [mumumusuc/termux-android-sdk#2]
Kindly tell me how to do this 

edit android/gradle.properties and add this line

android.aapt2FromMavenOverride=/data/data/com.termux/files/usr/opt/android-sdk/build-tools/30.0.3/aapt2
Where the android/gradle.properties found?

**Comment by mumumusuc** [comment]
under your flutter project, maybe `hello_world`, it's `<hello_world>/android/gradle.properties`, I make it more clear.

**Comment by L4R-777** [comment]
Web build working fine, THQ.
Your telegram username would be better for fixing something
